REM Assumption: route_guide_server.exe or route_guide_callback_server.exe is already running

route_guide_client.exe
route_guide_callback_client.exe
route_guide_coroutine_client.exe
route_guide_coroutine_client2.exe
