REM Assumption: multigreeter_server.exe is already running

multigreeter_client.exe

multigreeter_coroutine_client_nc.exe
multigreeter_coroutine_client2_nc.exe
multigreeter_coroutine_client3_nc.exe

multigreeter_coroutine_client_ee.exe
multigreeter_coroutine_client_el.exe
multigreeter_coroutine_client_le.exe
multigreeter_coroutine_client_ll.exe

multigreeter_coroutine_client2_ee.exe
multigreeter_coroutine_client2_el.exe
multigreeter_coroutine_client2_le.exe
multigreeter_coroutine_client2_ll.exe

multigreeter_coroutine_client3_ee.exe
multigreeter_coroutine_client3_el.exe
multigreeter_coroutine_client3_le.exe
multigreeter_coroutine_client3_ll.exe
