REM Assumption: greeter_server.exe (or greeter_async_server.exe or greeter_callback_server.exe) is already running

greeter_client.exe

greeter_async_client.exe
REM The following program does not terminate
REM greeter_async_client2.exe

greeter_callback_client.exe

greeter_cb_coroutine_client_xe.exe
greeter_cb_coroutine_client_xl.exe

greeter_cb_coroutine_client2_xe.exe
greeter_cb_coroutine_client2_xl.exe

greeter_cb_coroutine_client3_xe.exe
greeter_cb_coroutine_client3_xl.exe

greeter_coroutine_client_ee.exe
greeter_coroutine_client_el.exe
REM The following 2 programs block at run-time. See source code for explanation.
REM greeter_coroutine_client_le.exe
REM greeter_coroutine_client_ll.exe

greeter_coroutine_client2_ee.exe
greeter_coroutine_client2_el.exe
greeter_coroutine_client2_le.exe
greeter_coroutine_client2_ll.exe

greeter_coroutine_client2a_ee.exe
greeter_coroutine_client2a_el.exe
greeter_coroutine_client2a_le.exe
greeter_coroutine_client2a_ll.exe
