REM Assumption: multiplex_server.exe is already running

multiplex_client.exe
multiplex_client2.exe

multiplex_coroutine_client2_ee.exe
multiplex_coroutine_client2_el.exe
multiplex_coroutine_client2_le.exe
multiplex_coroutine_client2_ll.exe

multiplex_coroutine_client3_ee.exe
multiplex_coroutine_client3_el.exe
multiplex_coroutine_client3_le.exe
multiplex_coroutine_client3_ll.exe

multiplex_coroutine_client3-when_all_ee.exe
multiplex_coroutine_client3-when_all_el.exe
multiplex_coroutine_client3-when_all_le.exe
multiplex_coroutine_client3-when_all_ll.exe

multiplex_coroutine_client3-when_any_ee.exe
multiplex_coroutine_client3-when_any_el.exe
multiplex_coroutine_client3-when_any_le.exe
multiplex_coroutine_client3-when_any_ll.exe

multiplex_coroutine_client3-all_ee.exe
multiplex_coroutine_client3-all_el.exe
multiplex_coroutine_client3-all_le.exe
multiplex_coroutine_client3-all_ll.exe

multiplex_coroutine_client4_ee.exe
multiplex_coroutine_client4_el.exe
multiplex_coroutine_client4_le.exe
multiplex_coroutine_client4_ll.exe

multiplex_coroutine_client5_ee.exe
multiplex_coroutine_client5_el.exe
multiplex_coroutine_client5_le.exe
multiplex_coroutine_client5_ll.exe
